-- MySQL Script generated by MySQL Workbench
-- Wed Dec 28 22:21:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_parking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_parking` DEFAULT CHARACTER SET utf8 ;
USE `car_parking` ;

-- -----------------------------------------------------
-- Table `car_parking`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_parking`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_parking`.`tbl_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_parking`.`tbl_owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_parking`.`tbl_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_parking`.`tbl_car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_model` VARCHAR(255) NOT NULL,
  `license_plate` VARCHAR(255) NOT NULL,
  `tbl_owner_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_owner_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tbl_car_tbl_owner1_idx` (`tbl_owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_car_tbl_owner1`
    FOREIGN KEY (`tbl_owner_id`)
    REFERENCES `car_parking`.`tbl_owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_parking`.`tbl_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_parking`.`tbl_register` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `entry_time` TIME NOT NULL,
  `departure_time` TIME NOT NULL,
  `tbl_user_id` INT NOT NULL,
  `tbl_car_id` INT NOT NULL,
  `tbl_car_tbl_owner_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_user_id`, `tbl_car_id`, `tbl_car_tbl_owner_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tbl_register_tbl_user_idx` (`tbl_user_id` ASC) VISIBLE,
  INDEX `fk_tbl_register_tbl_car1_idx` (`tbl_car_id` ASC, `tbl_car_tbl_owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_register_tbl_user`
    FOREIGN KEY (`tbl_user_id`)
    REFERENCES `car_parking`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_register_tbl_car1`
    FOREIGN KEY (`tbl_car_id` , `tbl_car_tbl_owner_id`)
    REFERENCES `car_parking`.`tbl_car` (`id` , `tbl_owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
